version: '3.9'

services:
  writer:
    build: ./writer
    volumes:
      - shared_data:/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M

  reader:
    build: ./reader
    volumes:
      - shared_data:/data
    depends_on:
      - writer
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M

volumes:
  shared_data: